version: "3.8"
services:
  foot_pedal:
    container_name: foot_pedal
    env_file: .env
    build:
      context: .
      dockerfile: build/Dockerfile
    privileged: true
    volumes:
      - ./worker:/app/worker
    restart: always